//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.Diponivel = true;
            this.Promocao = new HashSet<Promocao>();
            this.EncomendaProduto = new HashSet<EncomendaProduto>();
        }
    
        public System.Guid Id { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataRegisto { get; set; }
        public string NumeroSerie { get; set; }
        public int TempoGarantia { get; set; }
        public decimal Preco { get; set; }
        public byte[] Imagem { get; set; }
        public System.Guid CategoriaId { get; set; }
        public System.Guid UtilizadorId { get; set; }
        public bool Diponivel { get; set; }
        public string ImagemTipo { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Utilizador Utilizador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promocao> Promocao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncomendaProduto> EncomendaProduto { get; set; }
    }
}
